- repo: local
  hooks:
    - id: prettier
      name: prettier
      entry: ./node_modules/.bin/prettier
      language: node
      stages: [commit]
      files: ^(static/)*.js
      args: ["--write"]
