# Generated by Django 3.2.20 on 2024-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_merge_20240413_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paypalcurrency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('EUR', 'Euros'), ('GBP', 'Pound sterling')], default='USD', max_length=8, verbose_name='Currency'),
        ),
    ]
