# Generated by Django 3.2.20 on 2024-08-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0041_merge_20240729_1306'),
        ('tracker', '0041_merge_20240829_1326'),
    ]

    operations = [
    ]
