# Generated by Django 5.1.2 on 2024-10-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0042_merge_20240829_1905'),
        ('tracker', '0048_merge_20241014_0900'),
    ]

    operations = [
    ]
