# Generated by Django 5.1.2 on 2024-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_add_milestone_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('CAD', 'Canadian Dollars'), ('EUR', 'Euros'), ('GBP', 'Pound sterling')], max_length=8, verbose_name='Currency'),
        ),
    ]
