# Generated by Django 5.1.2 on 2024-12-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0049_merge_20241215_1449'),
        ('tracker', '0050_alter_donation_currency'),
    ]

    operations = [
    ]
