# Generated by Django 5.1.2 on 2024-12-15 15:03

import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_delete_interview_text_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='charity_split',
            field=models.IntegerField(default=100, help_text='How much of the money is going to the charity, in percentages', validators=[tracker.validators.positive, tracker.validators.max_100], verbose_name='Charity Split'),
        ),
    ]
