# Generated by Django 5.1.2 on 2025-01-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0052_event_chairty_split'),
        ('tracker', '0055_merge_20250119_1022'),
    ]

    operations = [
    ]
