# Generated by Django 5.1.2 on 2025-01-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_add_euros_to_donation_and_event'),
        ('tracker', '0040_alter_event_paypalcurrency'),
        ('tracker', '0050_alter_donation_currency'),
        ('tracker', '0052_event_chairty_split'),
        ('tracker', '0058_remove_deprecated_runners'),
    ]

    operations = [
    ]
