# Generated by Django 5.1.2 on 2025-03-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_alter_event_paypalcurrency'),
        ('tracker', '0050_alter_donation_currency'),
        ('tracker', '0052_event_chairty_split'),
        ('tracker', '0063_add_receiver_fields'),
    ]

    operations = [
    ]
