# Generated by Django 5.1.2 on 2025-03-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0064_merge_20250301_0751'),
        ('tracker', '0064_remove_bid_pinned'),
    ]

    operations = [
    ]
