# Generated by Django 5.1.2 on 2025-04-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0065_add_donation_groups'),
        ('tracker', '0065_merge_0064_merge_20250301_0751_0064_remove_bid_pinned'),
    ]

    operations = [
    ]
