# Generated by Django 5.1.2 on 2025-05-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0066_merge_20250411_1701'),
        ('tracker', '0067_add_event_draft_column'),
    ]

    operations = [
    ]
