# Generated by Django 5.1.2 on 2025-07-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0068_merge_20250522_1321'),
        ('tracker', '0077_alter_prize_imagefile'),
    ]

    operations = [
    ]
