# Generated by Django 5.1.2 on 2025-09-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0078_merge_20250722_1549'),
        ('tracker', '0081_merge_20250731_2009'),
    ]

    operations = [
    ]
